### ISSUE TITLE
Some tests now failing

### ISSUE THREAD

**Issue by lucs** [zostay/perl6-IO-Glob#4]
Not sure why this happens now, but some tests fail. The code appears to be fixed by having`my @parts = (~$path).split...` instead of just `my @parts = $path.split...` in `multi method ACCEPTS(IO::Path:D $path)` in `Glob.pm`.

**Comment by zostay** [comment]
Thanks. It's because the thing being matched is an IO::Path. Previously, each path would be automatically coerced to Cool as the filename and then a string-like split would be called upon the file name. Now, however, paths have their own split method which slurps the contents of the file represented and then splits the contents to return.

Patching.
